---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-istio-deploy
  namespace: test-services
  labels:
    app: ms-istio
spec:
  selector:
    matchLabels:
      app: ms-istio
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-istio
    spec:
      containers:
        - name: ms-istio
          image: acjimeneza/ms-istio:1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-istio
  namespace: test-services
  labels:
    app: ms-istio
spec:
  type: ClusterIP
  selector:
    app: ms-istio
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
